### ISSUE TITLE
Problem with installation.

### ISSUE THREAD

**Issue by petarkozic** [giacomos/checkmk_hipchat_notifications#3]
Dear,

I was doing everything you said, but I give this error:

OMD[monitor]:~$ check_mk -vP install hipchat-1.2.mkp 
Traceback (most recent call last):
  File "/omd/sites/monitor/share/check_mk/modules/check_mk.py", line 5641, in <module>
    do_packaging(args)
  File "/omd/sites/monitor/share/check_mk/modules/packaging.py", line 99, in do_packaging
    f(args)
  File "/omd/sites/monitor/share/check_mk/modules/packaging.py", line 335, in package_install
    tar = tarfile.open(path, "r:gz")
  File "/usr/lib/python2.7/tarfile.py", line 1678, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/usr/lib/python2.7/tarfile.py", line 1730, in gzopen
    raise ReadError("not a gzip file")
tarfile.ReadError: not a gzip file

Please, help me if you can !

**Comment by petarkozic** [comment]
I was resolve the problem. Sorry, thank you :)

**Comment by SavaNDragos** [comment]
Any chance to get the description of how you fixed it?

**Comment by SavaNDragos** [comment]
SO i should wget https://github.com/giacomos/checkmk_hipchat_notifications/raw/master/hipchat-1.2.mkp
